name: Generate courses

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'

concurrency: generate-courses

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install Intermediate Certificates
        run: |
          openssl s_client -showcerts -servername students.technion.ac.il -connect students.technion.ac.il:443 | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' > ~/technion.crt
          sudo mv ~/technion.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates
      - name: Generate courses
        run: |
          cd main
          bash deploy.sh ../gh-pages
        env:
          MOODLE_SESSIONSTUDENTSPROD: ${{ secrets.MOODLE_SESSIONSTUDENTSPROD }}
          COURSE_INFO_FETCHER_PROXY: ${{ secrets.COURSE_INFO_FETCHER_PROXY }}
          COURSE_INFO_FETCHER_PROXY_URL: ${{ secrets.COURSE_INFO_FETCHER_PROXY_URL }}
          COURSE_INFO_FETCHER_PROXY_AUTH: ${{ secrets.COURSE_INFO_FETCHER_PROXY_AUTH }}
      - name: Deploy
        run: |
          cd gh-pages
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff-index --quiet --cached HEAD || git commit -m "Update courses"
          git push
